spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/tournament?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true'
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db_username}  # Ensure these environment variables are set
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  application:
    name: AuthenticationService

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
      nodeValue: WARN
    blog: WARN
