spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/tournament?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}  # Ensure these environment variables are set
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  application:
    name: AuthenticationService

jwt:
  secretkey: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"  # Ensure this environment variable is set

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
      nodeValue: WARN
    blog: WARN
