package bg.softuni.userservice.models.enums;



public enum PermissionEnum {
    MANAGE_ALL_USERS,
    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_FIRST_NAME,
    CHANGE_LAST_NAME,
    CHANGE_EMAIL,
    MANAGE_FRIENDS,
    MANAGE_OWN_PROFILE,
    MANAGE_ALL_TEAMS,
    VIEW_TEAM,
    MANAGE_TEAM,
    MANAGE_ALL_TOURNAMENTS,
    VIEW_TOURNAMENT,
    MANAGE_TOURNAMENT
}
